<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
	<ecore:EPackage name="TypeA" nsURI="http://www.eclipse.org/atl/atlTransformations/TypeA" nsPrefix="TypeA">
	  <eClassifiers xsi:type="ecore:EClass" name="BlockA">
		<eStructuralFeatures xsi:type="ecore:EReference" name="inputPorts" upperBound="-1"
			eType="#//PortA" containment="true"/>
		<eStructuralFeatures xsi:type="ecore:EReference" name="outputPorts" upperBound="-1"
			eType="#//PortA" containment="true"/>
	  </eClassifiers>
	  <eClassifiers xsi:type="ecore:EClass" name="PortA">
		<eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
	  </eClassifiers>
	</ecore:EPackage>
</xmi:XMI>
